import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col h-screen min-[1800px]:h-screen no-scrollbar overflow-hidden ${inter.className}`}
      >
        <div className="h-full  overflow-y-auto no-scrollbar">
          <Header />

          <div className="flex-1 h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
